### ISSUE TITLE
'Member' object has no attribute 'game'

### ISSUE THREAD

**Issue by ThisIsTenou** [Neolysion/Discord-Auto-Renamer#1]
`Ignoring exception in on_member_update
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "autorenamer.py", line 39, in on_member_update
    if before.game != after.game:
AttributeError: 'Member' object has no attribute 'game'`

This message is being sent almost every second. The bot doesn't seem to do anything, so it's a rather big issue.

**Comment by s-boris** [comment]
9db13e44a689470d93a1d40c0c5c97b9e4d22488
It should support the latest discord.py version now. I could only test it myself with 2 discord accounts in a channel though.

**Comment by ThisIsTenou** [comment]
Hey @JuicyM, it works flawlessly now. Thank you very much!
